# Generated by Django 6.0.5 on 2026-05-14 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobcategory_skill_remove_job_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('freelancer', 'job')},
        ),
    ]
