# Generated by Django 6.0 on 2026-05-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_savedjob_unique_together'),
        ('jobs', '0004_job_deadline'),
    ]

    operations = [
    ]
