# Generated by Django 6.0.5 on 2026-05-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_merge_20260515_0511'),
        ('jobs', '0005_merge_20260515_0512'),
    ]

    operations = [
    ]
