# Generated by Django 6.0.5 on 2026-05-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_experience_level_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_level',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote'), ('contract', 'Contract')], default='remote', max_length=20),
        ),
    ]
