# Generated by Django 5.2.13 on 2026-05-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_application_id_alter_contract_id_alter_job_id_and_more'),
        ('jobs', '0009_job_experience_level_alter_job_category_and_more'),
    ]

    operations = [
    ]
