# Generated by Django 6.0.5 on 2026-05-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_application_id_alter_contract_id_alter_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
