# Generated by Django 6.0 on 2026-05-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('companyname', models.CharField(blank=True, max_length=200)),
                ('companydescription', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('nidnumber', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('universityname', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField()),
                ('experience', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('portfolio_link', models.URLField(blank=True)),
                ('githublink', models.URLField(blank=True)),
                ('linkedinlink', models.URLField(blank=True)),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('nidnumber', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
