# Generated by Django 5.2.13 on 2026-05-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_clientprofile_id_alter_freelancerprofile_id'),
        ('users', '0002_alter_clientprofile_profileimage_and_more'),
    ]

    operations = [
    ]
