# Generated by Django 6.0.5 on 2026-05-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20260515_1501'),
        ('users', '0004_alter_clientprofile_id_alter_freelancerprofile_id'),
    ]

    operations = [
    ]
