# Generated by Django 5.2.13 on 2026-05-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20260515_1257'),
        ('users', '0005_merge_20260515_2041'),
    ]

    operations = [
    ]
