# Generated by Django 6.0.5 on 2026-05-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_id'),
        ('users', '0009_alter_clientprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='users.clientprofile'),
        ),
    ]
